FROM python:3.12-slim

# Instalar dependencias necesarias del sistema
RUN apt-get update && apt-get install -y libpq-dev gcc && apt-get clean && rm -rf /var/lib/apt/lists/*

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar archivos de configuración de poetry
COPY pyproject.toml poetry.lock* /app/

# Instalar poetry
RUN pip install poetry && \
    poetry config virtualenvs.in-project true && \
    poetry install --no-root && \
    echo 'export PATH="/app/.venv/bin:$PATH"' >> ~/.bashrc

# Copiar el resto de la aplicación
COPY ./ /app

# Configurar el entorno virtual como predeterminado
ENV PATH="/app/.venv/bin:$PATH"

# Exponer el puerto de la aplicación
EXPOSE 5000

CMD ["python3", "run.py"]
