# Use a python image
FROM python:3.12-slim

# Poetry environment variables
ENV POETRY_VERSION=1.8.1 \
    POETRY_HOME="/opt/poetry" \
    POETRY_VIRTUALENVS_IN_PROJECT=true \
    POETRY_NO_INTERACTION=1

# Install Poetry
RUN apt-get update && apt-get install -y curl && \
    curl -sSL https://install.python-poetry.org | python3 - && \
    ln -s $POETRY_HOME/bin/poetry /usr/local/bin/poetry

# Set the working directory
WORKDIR /app

# Copy project files
COPY pyproject.toml poetry.lock ./

# Install project dependencies
RUN poetry install --no-root --verbose

# Copy the rest of the project code
COPY . .

# Specify the command to run the application
# CMD ["poetry", "run", "python", "main.py"]
CMD ["poetry", "install", "--verbose"]
